### ISSUE TITLE
Unable to install Plugin fluent-plugin-mysql-binlog

### ISSUE THREAD

**Issue by satyaakam** [izumiya/fluent-plugin-mysql-binlog#3]
When i try the  /usr/sbin/td-agent-gem install  fluent-plugin-mysql-binlog as root i am getting following errors i have installed all development packages , i am trying this install on Centos 5.8 

Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-mysql-binlog:
    ERROR: Failed to build gem native extension.

```
/opt/td-agent/embedded/bin/ruby extconf.rb
```

checking for main() in -lstdc++... **\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/opt/td-agent/embedded/bin/ruby
    --with-stdc++lib
    --without-stdc++lib
/opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:541:in`try_link0'
    from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
    from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:742:in`try_func'
    from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:973:in `block in have_library'
    from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:918:in`block in checking_for'
    from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
    from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in`open'
    from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
    from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in`open'
    from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
    from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:917:in`checking_for'
    from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:968:in `have_library'
    from extconf.rb:3:in`<main>'

extconf failed, exit code 1

Gem files will remain installed in /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-binlog-0.1.9 for inspection.
Results logged to /opt/td-agent/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/ruby-binlog-0.1.9/gem_make.out

**Comment by satyaakam** [comment]
same result when i try 

/opt/td-agent/embedded/bin/fluent-gem install  fluent-plugin-mysql-binlog
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.4.3)
      cool.io (< 2.0.0, >= 1.2.2)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-mysql-binlog:
    ERROR: Failed to build gem native extension.

```
/opt/td-agent/embedded/bin/ruby extconf.rb
```

checking for main() in -lstdc++... yes
checking for main() in -lreplication... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/opt/td-agent/embedded/bin/ruby
    --with-stdc++lib
    --without-stdc++lib
    --with-replicationlib
    --without-replicationlib

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.2.0/gems/ruby-binlog-0.1.9 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.2.0/extensions/x86_64-linux/2.1.0/ruby-binlog-0.1.9/gem_make.out
You have new mail in /var/spool/mail/root

**Comment by waltsims** [comment]
I'm having the same problem. Did you find any solution?
